from __future__ import annotations

from enum import Enum


class JobStatus(str, Enum):
    RECEIVED = "RECEIVED"
    FILE_VALIDATED = "FILE_VALIDATED"
    QUALITY_CHECKED = "QUALITY_CHECKED"
    PREPROCESSED = "PREPROCESSED"
    OCR_COMPLETED = "OCR_COMPLETED"
    OCR_VALIDATED = "OCR_VALIDATED"
    EXTRACTING = "EXTRACTING"
    EXTRACTED = "EXTRACTED"
    SCHEMA_VALIDATED = "SCHEMA_VALIDATED"
    BUSINESS_VALIDATED = "BUSINESS_VALIDATED"
    DUPLICATE_CHECKED = "DUPLICATE_CHECKED"
    CONFIDENCE_SCORED = "CONFIDENCE_SCORED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    REGISTERING = "REGISTERING"
    REGISTERED = "REGISTERED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"


class InReviewState(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class ExtractionMode(str, Enum):
    PDF_TEXT = "PDF_TEXT"
    OCR_TEXT = "OCR_TEXT"
    VISION = "VISION"


class ReasonCode(str, Enum):
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    PARTNER_NOT_FOUND = "PARTNER_NOT_FOUND"
    UNKNOWN_TAX_RATE = "UNKNOWN_TAX_RATE"
    AMOUNT_MISMATCH = "AMOUNT_MISMATCH"
    INVALID_DATE = "INVALID_DATE"
    DUPLICATE_INVOICE = "DUPLICATE_INVOICE"
    DUPLICATE_FILE = "DUPLICATE_FILE"
    OCR_UNRELIABLE = "OCR_UNRELIABLE"
    HANDWRITING = "HANDWRITING"
    VISION_EXTRACTION_UNCERTAIN = "VISION_EXTRACTION_UNCERTAIN"
    UNSUPPORTED_FILE = "UNSUPPORTED_FILE"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    CORRUPTED_FILE = "CORRUPTED_FILE"
    EMPTY_FILE = "EMPTY_FILE"
    DOCUMENT_NOT_DETECTED = "DOCUMENT_NOT_DETECTED"
    IMAGE_CUTOFF = "IMAGE_CUTOFF"
    IMAGE_UNREADABLE = "IMAGE_UNREADABLE"
    NOT_AN_INVOICE = "NOT_AN_INVOICE"
    SCHEMA_INVALID = "SCHEMA_INVALID"
    UNABLE_TO_EXTRACT = "UNABLE_TO_EXTRACT"
    ACCOUNTING_REJECTED = "ACCOUNTING_REJECTED"